name: HTML5

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build_Test-Linux-WASI:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/swiftwasm/carton:latest
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Swift Version
      run: swift --version
    
    - name: Bundle
      run: carton bundle
    - name: Test
      run: carton test --environment node
