name: Linux

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build_Test-Linux-Linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deps
      run: sudo apt-get install freeglut3-dev; sudo apt-get install libopenal-dev
    
    - name: Swift Version
      run: swift --version
      
    - name: Build
      run: swift build
    - name: Test
      run: swift test
