name: Linux

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build_Test-Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deps
      run: apt-get install freeglut3-dev
    - name: Build
      run: swift build
    - name: Test
      run: swift test
