name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macOS:
    
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.3.app/Contents/Developer'
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build
    - name: Test
      run: swift test
