name: Windows

on:
  workflow_dispatch:
  push:
    branches:
    - '**' # matches every branch
  pull_request:
    branches:
    - 'main'

jobs:
  Build_Test-Windows-Windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.8-release
          tag: 5.8-RELEASE
      - uses: actions/checkout@v3
      
      - name: Swift Version
        run: swift --version
      
      - name: Build
        run: swift build
      - name: Test
        run: swift test
